### ISSUE TITLE
[Feat] 스크랩 디렉토리 이사

### ISSUE THREAD

**Issue by HaydenDevK** [sturing-fourten/sturing#29]
## TYPE
- [ ] UI
- [ ] Feat
- [ ] Fix
- [x] Refactor
- [ ] Chore

## ✏️작업 상세 내용
- [ ] /mypage/scrap을 /(userProfile)/mypage 하위로 이동

**Comment by Yoon-kyungLee** [comment]
ㅋㅋㅋ 이사가자~
